options:
  logging: CLOUD_LOGGING_ONLY  # Sends logs to Cloud Logging

steps:
  # Install dependencies with execution permissions
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--unsafe-perm']

  # Fix file permissions for Vite before running the build
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: bash
    args:
      - '-c'
      - 'chmod +x node_modules/.bin/vite'

  # Build the React app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Use Google Cloud Buildpacks (Ensure correct image reference)
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'gcr.io/micro-shift-449410-a1/react-app'  # Use $PROJECT_ID instead of hardcoding
      - '--builder=gcr.io/buildpacks/builder:v1'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'react-app'
      - '--image'
      - 'gcr.io/micro-shift-449410-a1/react-app'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/micro-shift-449410-a1/react-app'
